apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity
  labels:
    env: test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:   # this is hard rule
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1a
            - us-east-1d

      preferredDuringSchedulingIgnoredDuringExecution:  # this is soft rule
      - weight: 100
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshopp

      - weight: 10
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - amazon
  containers:
  - name: nginx
    image: nginx