apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity
  labels:
    env: test
spec:
  affinity:
    nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1a
  containers:
  - name: nginx
    image: nginx